import Navigation from '@/components/Navigation'
import Footer from '@/components/Footer'
import ScrollProgress from '@/components/ScrollProgress'
import StickyBar from '@/components/StickyBar'
import MobileCTA from '@/components/MobileCTA'

export default function TermsAndConditionsPage() {
  return (
    <div id="app-wrapper" className="w-full h-full overflow-auto">
      <ScrollProgress />
      <StickyBar />
      <Navigation />
      
      <main className="bg-clean-white py-24 px-6 md:px-12 lg:px-24">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="mb-16 text-center lg:text-left">
            <span className="font-mono text-success-gold text-xs tracking-[0.3em] uppercase font-bold block mb-4">Agreement Framework</span>
            <h1 className="text-4xl md:text-6xl font-heading font-extrabold text-authority mb-8 leading-tight">
              Terms and <span className="gradient-text">Conditions</span>
            </h1>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 p-6 glass-card-light rounded-2xl border border-authority/5">
              <div>
                <div className="text-[10px] font-mono text-authority/40 uppercase tracking-tighter">Effective Date</div>
                <div className="text-sm font-heading font-bold text-authority">March 5, 2026</div>
              </div>
              <div>
                <div className="text-[10px] font-mono text-authority/40 uppercase tracking-tighter">Entity</div>
                <div className="text-sm font-heading font-bold text-authority">Career Charm / InfoArbol</div>
              </div>
              <div>
                <div className="text-[10px] font-mono text-authority/40 uppercase tracking-tighter">Location</div>
                <div className="text-sm font-heading font-bold text-authority">Faridkot, Punjab, India</div>
              </div>
            </div>
          </div>

          {/* Sections */}
          <div className="space-y-12">
            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">1</span>
                Acceptance of Terms & Eligibility
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>By accessing the Career Charm website or mobile application, you acknowledge that you have read, understood, and agreed to be bound by these Terms and Conditions.</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><span className="text-authority font-semibold">Minors and Guardianship:</span> Our primary audience includes students under the age of 18. Use of the platform by a minor is strictly conditional upon the consent of a parent or legal guardian.</li>
                  <li><span className="text-authority font-semibold">Consent:</span> By allowing a minor to use the service or by making a purchase, the parent/guardian agrees to take full responsibility for the minor&apos;s data sharing, financial transactions, and adherence to these terms.</li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">2</span>
                Intellectual Property (IP) Protection
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>All content, logic, and output generated by Career Charm are the exclusive intellectual property of InfoArbol.</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><span className="text-authority font-semibold">Proprietary Assets:</span> This includes, but is not limited to, the Binary CPT Algorithm, the 16 Career Archetypes, the methodology of our aptitude tests, and the proprietary 25-page &quot;Scientific Career Blueprints.&quot;</li>
                  <li><span className="text-authority font-semibold">Usage License:</span> Upon purchase, the user is granted a non-exclusive, non-transferable, personal license to view the report for individual career planning.</li>
                </ul>
                <div className="p-6 glass-card rounded-2xl border-l-4 border-authority/20 bg-authority/[0.02]">
                  <h4 className="text-authority font-bold mb-2">Strict Prohibitions:</h4>
                  <ul className="list-disc pl-5 space-y-1 text-sm">
                    <li>Reselling, redistributing, or sub-licensing the reports.</li>
                    <li>Publicly sharing full reports on social media or public forums without written consent.</li>
                    <li>Using any automated system (scraping) to extract data from the app or website.</li>
                  </ul>
                </div>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">3</span>
                Payment, Subscriptions & &quot;No-Refund&quot; Policy
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>Career Charm operates on a hybrid model of subscriptions and one-time purchases.</p>
                <div className="grid md:grid-cols-2 gap-4 mb-4">
                  <div className="p-4 glass-card-light rounded-xl border border-growth-blue/10">
                    <div className="text-xs font-mono text-growth-blue uppercase tracking-widest mb-1">Monthly Subscription</div>
                    <div className="text-xl font-bold text-authority">₹1,999</div>
                  </div>
                  <div className="p-4 glass-card-light rounded-xl border border-success-gold/10">
                    <div className="text-xs font-mono text-success-gold uppercase tracking-widest mb-1">Annual Subscription</div>
                    <div className="text-xl font-bold text-authority">₹2,999</div>
                  </div>
                </div>
                <p className="text-sm font-medium italic">Note: In-app courses are separate &quot;add-on&quot; purchases and are not included in the standard subscription unless explicitly stated.</p>
                
                <div className="space-y-4 pt-4 border-t border-authority/5">
                  <h4 className="text-authority font-bold flex items-center gap-2">
                    <svg className="w-5 h-5 text-success-gold" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M2.166 4.999A11.954 11.954 0 0010 1.944 11.954 11.954 0 0017.834 5c.11.65.166 1.32.166 2.001 0 5.225-3.34 9.67-8 11.317C5.34 16.67 2 12.225 2 7c0-.682.057-1.35.166-2.001zm11.541 3.708a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    The No-Refund Shield
                  </h4>
                  <p>Due to the nature of digital goods, the Scientific Career Blueprint is considered &quot;consumed&quot; the moment the PDF is generated or accessed.</p>
                  <ul className="list-disc pl-5 space-y-2">
                    <li><span className="text-authority font-semibold">Strict Policy:</span> All sales are final. No refunds will be issued once the psychometric assessment is completed or the digital report is delivered.</li>
                    <li><span className="text-authority font-semibold">Exceptions:</span> Refunds will only be considered in the event of a double-billing error caused by a technical glitch in our payment gateway.</li>
                  </ul>
                </div>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">4</span>
                Disclaimer of Liability
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>Career Charm provides a &quot;Guidance Tool,&quot; not a &quot;Result Guarantee.&quot;</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><span className="text-authority font-semibold">Nature of Reports:</span> Reports are generated based on psychometric algorithms and current market trends. They represent statistical probabilities, not absolute certainties.</li>
                  <li><span className="text-authority font-semibold">No Guarantees:</span> Career Charm/InfoArbol does not guarantee admission to specific institutions, specific salary brackets, or the future accuracy of market trends.</li>
                  <li><span className="text-authority font-semibold">Limitation of Liability:</span> InfoArbol shall not be held liable for any career decisions, emotional distress, or financial losses incurred by the user based on the suggestions provided.</li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">5</span>
                Data Privacy & DPDP Compliance
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>In compliance with the Digital Personal Data Protection (DPDP) Act, 2023, we prioritize the security of student data.</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><span className="text-authority font-semibold">Processing Consent:</span> By using our assessment tools, users provide explicit consent for InfoArbol to process psychometric and personal data.</li>
                  <li><span className="text-authority font-semibold">Data Usage:</span> Data is used solely for the improvement of the algorithm and the delivery of the service. We do not sell user-specific data to third-party marketing firms.</li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">6</span>
                User Conduct & Account Termination
              </h2>
              <div className="pl-11 space-y-4 text-authority/70 text-sm">
                <p>We reserve the right to suspend or terminate any account, without notice, if a user attempts to reverse-engineer our algorithm, provides fraudulent information, or engages in account sharing.</p>
              </div>
            </section>

            <section className="p-8 md:p-12 glass-card rounded-[3rem] border border-growth-blue/10 bg-authority text-white relative overflow-hidden">
              <div className="absolute inset-0 grid-lines opacity-10"></div>
              <div className="relative z-10">
                <h2 className="text-2xl font-heading font-bold text-white flex items-center gap-3 mb-6">
                  <span className="w-8 h-8 rounded-lg bg-white/10 flex items-center justify-center text-white text-sm">7</span>
                  Governing Law & Jurisdiction
                </h2>
                <p className="text-white/60 mb-6 pl-11">
                  These terms shall be governed by and construed in accordance with the laws of India. Any dispute, controversy, or claim arising out of these terms shall be subject to the exclusive jurisdiction of the courts located in <span className="text-white font-bold">Faridkot, Punjab, India</span>.
                </p>
              </div>
            </section>
          </div>
        </div>
      </main>

      <Footer />
      <MobileCTA />
    </div>
  )
}
