import Navigation from '@/components/Navigation'
import Footer from '@/components/Footer'
import ScrollProgress from '@/components/ScrollProgress'
import StickyBar from '@/components/StickyBar'
import MobileCTA from '@/components/MobileCTA'

export default function PrivacyPolicyPage() {
  return (
    <div id="app-wrapper" className="w-full h-full overflow-auto">
      <ScrollProgress />
      <StickyBar />
      <Navigation />
      
      <main className="bg-clean-white py-24 px-6 md:px-12 lg:px-24">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="mb-16 text-center lg:text-left">
            <span className="font-mono text-success-gold text-xs tracking-[0.3em] uppercase font-bold block mb-4">Legal Framework</span>
            <h1 className="text-4xl md:text-6xl font-heading font-extrabold text-authority mb-8 leading-tight">
              Privacy Policy: <span className="gradient-text">Career Charm & InfoArbol</span>
            </h1>
            
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-6 glass-card-light rounded-2xl border border-authority/5">
              <div>
                <div className="text-[10px] font-mono text-authority/40 uppercase tracking-tighter">Last Updated</div>
                <div className="text-sm font-heading font-bold text-authority">March 5, 2026</div>
              </div>
              <div>
                <div className="text-[10px] font-mono text-authority/40 uppercase tracking-tighter">Entity</div>
                <div className="text-sm font-heading font-bold text-authority">InfoArbol</div>
              </div>
              <div>
                <div className="text-[10px] font-mono text-authority/40 uppercase tracking-tighter">Application</div>
                <div className="text-sm font-heading font-bold text-authority">Career Charm</div>
              </div>
              <div>
                <div className="text-[10px] font-mono text-authority/40 uppercase tracking-tighter">Jurisdiction</div>
                <div className="text-sm font-heading font-bold text-authority">Faridkot, Punjab</div>
              </div>
            </div>
          </div>

          {/* Introduction */}
          <div className="prose prose-lg max-w-none text-authority/70 leading-relaxed mb-16">
            <p className="text-xl italic font-display text-authority/80">
              At InfoArbol, we recognize that your data—and specifically your child’s career aspirations—is personal and sensitive. This Privacy Policy outlines how the Career Charm app collects, processes, and protects information to deliver the &quot;Scientific Career Blueprint.&quot;
            </p>
          </div>

          {/* Sections */}
          <div className="space-y-12">
            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">1</span>
                Data Collection & The &quot;Notice&quot; Requirement
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>In compliance with the DPDP Act, we collect only the minimum data necessary to provide our career counseling services.</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><span className="text-authority font-semibold">Data Provided by You (Registration):</span> Name, mobile number, email address (for OTP verification), and current academic grade/level etc.</li>
                  <li><span className="text-authority font-semibold">Data Generated by the App:</span> Responses to the Career Personality Test (CPT), Aptitude Test scores, and the resulting 16-archetype professional profile.</li>
                  <li><span className="text-authority font-semibold">Purpose of Collection:</span> We use this data solely to generate your 25-page Scientific Career Blueprint and to provide &quot;Zero-Search&quot; industry insights tailored to your specific profile.</li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">2</span>
                Mandatory Parental Consent for Minors
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>Since Career Charm primarily serves students, many of whom are under the age of 18, we adhere to strict &quot;Verifiable Parental Consent&quot; standards:</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><span className="text-authority font-semibold">Verification:</span> Users under 18 must provide a parent or guardian’s mobile number/email. Processing of the student’s data only commences once the parent has verified consent via a secure OTP (One-Time Password) or a digital consent checkbox.</li>
                  <li><span className="text-authority font-semibold">Protection:</span> We do not engage in any processing of personal data that is likely to cause detrimental effects on the well-being of a child.</li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">3</span>
                Purpose Limitation & Data Processing
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>We believe in transparency. Your data is used for one reason: Helping you build a successful career.</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><span className="text-authority font-semibold">No Data Sales:</span> We explicitly state that we do not sell your personal, psychometric, or aptitude data to third-party advertisers.</li>
                  <li><span className="text-authority font-semibold">Internal Improvement:</span> We may use anonymized, aggregated data (which cannot identify you) to improve our career matching algorithms and psychometric models.</li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">4</span>
                Rights of the Data Principal (Your Rights)
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>Under Indian law, you (and your parents/guardians) hold the following rights:</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><span className="text-authority font-semibold">Right to Access:</span> You may request a summary of the personal data we hold and the processing activities undertaken.</li>
                  <li><span className="text-authority font-semibold">Right to Correction & Erasure:</span> You can update inaccuracies or request the permanent deletion of your account and all associated psychometric data.</li>
                  <li><span className="text-authority font-semibold">Right to Withdraw Consent:</span> You may withdraw your consent at any time. Please note that withdrawing consent will result in the immediate cessation of app services and the inability to access your Career Blueprint.</li>
                  <li><span className="text-authority font-semibold">Right to Grievance Redressal:</span> If you have concerns about how your data is handled, you have the right to approach our Grievance Officer.</li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">5</span>
                Data Security Measures
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>We employ &quot;High-Tech&quot; security protocols to ensure your career data remains confidential:</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><span className="text-authority font-semibold">Encryption:</span> All data in transit is protected using SSL/TLS encryption.</li>
                  <li><span className="text-authority font-semibold">Secure Storage:</span> Personal and psychometric data are stored on secure cloud servers located within India.</li>
                  <li><span className="text-authority font-semibold">Hashing:</span> Sensitive information, including passwords, is protected using industry-standard cryptographic hashing to prevent unauthorized access.</li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">6</span>
                Third-Party Sharing
              </h2>
              <div className="pl-11 space-y-4 text-authority/70">
                <p>To provide a seamless experience, we partner with specialized service providers:</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><span className="text-authority font-semibold">Analytics:</span> We use tools like Google Analytics to understand app performance.</li>
                  <li><span className="text-authority font-semibold">Payments:</span> Secure transactions are handled via PCI-DSS compliant gateway (Razorpay). These partners are independent Data Processors and maintain their own rigorous privacy standards in accordance with the law.</li>
                </ul>
              </div>
            </section>

            <section className="p-8 md:p-12 glass-card rounded-[3rem] border border-growth-blue/10 bg-gradient-to-br from-growth-blue/[0.02] to-success-gold/[0.02]">
              <h2 className="text-2xl font-heading font-bold text-authority flex items-center gap-3 mb-8">
                <span className="w-8 h-8 rounded-lg bg-growth-blue/10 flex items-center justify-center text-growth-blue text-sm">7</span>
                Grievance Officer Details
              </h2>
              <div className="pl-11 grid md:grid-cols-2 gap-8">
                <div className="space-y-4">
                  <div>
                    <div className="text-xs font-mono text-authority/40 uppercase tracking-widest mb-1">Name</div>
                    <div className="text-lg font-heading font-bold text-authority">Ritik Sharma</div>
                  </div>
                  <div>
                    <div className="text-xs font-mono text-authority/40 uppercase tracking-widest mb-1">Designation</div>
                    <div className="text-authority font-medium">Grievance Officer & CEO</div>
                  </div>
                </div>
                <div className="space-y-4">
                  <div>
                    <div className="text-xs font-mono text-authority/40 uppercase tracking-widest mb-1">Email</div>
                    <a href="mailto:teamcareercharm@gmail.com" className="text-growth-blue font-bold hover:underline">teamcareercharm@gmail.com</a>
                  </div>
                  <div>
                    <div className="text-xs font-mono text-authority/40 uppercase tracking-widest mb-1">Address</div>
                    <div className="text-authority/70">Faridkot, Punjab, India, 151203</div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </main>

      <Footer />
      <MobileCTA />
    </div>
  )
}
